//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AeroWizard.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AeroWizard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BackBtnStrip {
            get {
                object obj = ResourceManager.GetObject("BackBtnStrip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap item {
            get {
                object obj = ResourceManager.GetObject("item", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ready {
            get {
                object obj = ResourceManager.GetObject("ready", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 返回上一步 的本地化字符串。
        /// </summary>
        internal static string WizardBackButtonToolTip {
            get {
                return ResourceManager.GetString("WizardBackButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;上一步 的本地化字符串。
        /// </summary>
        internal static string WizardBackText {
            get {
                return ResourceManager.GetString("WizardBackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;取消 的本地化字符串。
        /// </summary>
        internal static string WizardCancelText {
            get {
                return ResourceManager.GetString("WizardCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon WizardControlIcon {
            get {
                object obj = ResourceManager.GetObject("WizardControlIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;回收 的本地化字符串。
        /// </summary>
        internal static string WizardFinishText {
            get {
                return ResourceManager.GetString("WizardFinishText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page Title 的本地化字符串。
        /// </summary>
        internal static string WizardHeader {
            get {
                return ResourceManager.GetString("WizardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;帮助 的本地化字符串。
        /// </summary>
        internal static string WizardHelpText {
            get {
                return ResourceManager.GetString("WizardHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;下一步 的本地化字符串。
        /// </summary>
        internal static string WizardNextText {
            get {
                return ResourceManager.GetString("WizardNextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No wizard pages have been added. 的本地化字符串。
        /// </summary>
        internal static string WizardNoPagesNotice {
            get {
                return ResourceManager.GetString("WizardNoPagesNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤描述 的本地化字符串。
        /// </summary>
        internal static string WizardTitle {
            get {
                return ResourceManager.GetString("WizardTitle", resourceCulture);
            }
        }
    }
}
